import { createRouter, createWebHistory, RouteRecordRaw } from 'vue-router';
import Home from '../views/Homes.vue';



/* 路由 */
const routes: Array<RouteRecordRaw> = [
  {path: '/', name: 'Home', component: Home },
  {path: '/refresh', name: 'Refresh', component: ()=>import('../views/tools/Refresh.vue') },
  // Vue
  {path: '/vue/install/install', name: 'vue_install_install', component: ()=>import('../views/docs/vue/install/install.md') },
  {path: '/vue/install/index', name: 'vue_install_index', component: ()=>import('../views/docs/vue/install/index.md') },
  {path: '/vue/install/build', name: 'vue_install_build', component: ()=>import('../views/docs/vue/install/build.md') },
  {path: '/vue/install/icons', name: 'vue_install_icons', component: ()=>import('../views/docs/vue/install/icons.md') },
  // Flutter
  {path: '/flutter/install/install', name: 'flutter_install_install', component: ()=>import('../views/docs/flutter/install/install.md') },
  {path: '/flutter/install/index', name: 'flutter_install_index', component: ()=>import('../views/docs/flutter/install/index.md') },
  {path: '/flutter/install/build', name: 'flutter_install_build', component: ()=>import('../views/docs/flutter/install/build.md') },
  // PHP
  {path: '/php/install/install', name: 'php_install_install', component: ()=>import('../views/docs/php/install/install.md') },
  {path: '/php/install/index', name: 'php_install_index', component: ()=>import('../views/docs/php/install/index.md') },
  {path: '/php/install/build', name: 'php_install_build', component: ()=>import('../views/docs/php/install/build.md') },
  {path: '/php/service/base', name: 'php_service_base', component: ()=>import('../views/docs/php/service/base.md') },
  {path: '/php/service/data', name: 'php_service_data', component: ()=>import('../views/docs/php/service/data.md') },
  {path: '/php/service/logs', name: 'php_service_logs', component: ()=>import('../views/docs/php/service/logs.md') },
  {path: '/php/service/token', name: 'php_service_token', component: ()=>import('../views/docs/php/service/token.md') },
  {path: '/php/service/socket', name: 'php_service_socket', component: ()=>import('../views/docs/php/service/socket.md') },
  {path: '/php/db/model', name: 'php_db_model', component: ()=>import('../views/docs/php/db/model.md') },
  {path: '/php/db/select', name: 'php_db_select', component: ()=>import('../views/docs/php/db/select.md') },
  {path: '/php/db/insert', name: 'php_db_insert', component: ()=>import('../views/docs/php/db/insert.md') },
  {path: '/php/db/update', name: 'php_db_update', component: ()=>import('../views/docs/php/db/update.md') },
  {path: '/php/db/delete', name: 'php_db_delete', component: ()=>import('../views/docs/php/db/delete.md') },
  {path: '/php/db/join', name: 'php_db_join', component: ()=>import('../views/docs/php/db/join.md') },
  {path: '/php/db/commit', name: 'php_db_commit', component: ()=>import('../views/docs/php/db/commit.md') },
  {path: '/php/library/curl', name: 'php_library_curl', component: ()=>import('../views/docs/php/library/curl.md') },
  {path: '/php/library/export', name: 'php_library_export', component: ()=>import('../views/docs/php/library/export.md') },
  {path: '/php/library/qrcode', name: 'php_library_qrcode', component: ()=>import('../views/docs/php/library/qrcode.md') },
  {path: '/php/library/redis', name: 'php_library_redis', component: ()=>import('../views/docs/php/library/redis.md') },
  {path: '/php/library/safety', name: 'php_library_safety', component: ()=>import('../views/docs/php/library/safety.md') },
  {path: '/php/library/socket', name: 'php_library_socket', component: ()=>import('../views/docs/php/library/socket.md') },
  {path: '/php/library/upload', name: 'php_library_upload', component: ()=>import('../views/docs/php/library/upload.md') },
  {path: '/php/util/util', name: 'php_util_util', component: ()=>import('../views/docs/php/util/util.md') },
  {path: '/php/util/url', name: 'php_util_url', component: ()=>import('../views/docs/php/util/url.md') },
  {path: '/php/util/base64', name: 'php_util_base64', component: ()=>import('../views/docs/php/util/base64.md') },
  {path: '/php/util/hash', name: 'php_util_hash', component: ()=>import('../views/docs/php/util/hash.md') },
  {path: '/php/util/type', name: 'php_util_type', component: ()=>import('../views/docs/php/util/type.md') },
  {path: '/php/util/os', name: 'php_util_os', component: ()=>import('../views/docs/php/util/os.md') },
  // Flask
  {path: '/python/install/install', name: 'python_install_install', component: ()=>import('../views/docs/python/install/install.md') },
  {path: '/python/install/index', name: 'python_install_index', component: ()=>import('../views/docs/python/install/index.md') },
  {path: '/python/install/build', name: 'python_install_build', component: ()=>import('../views/docs/python/install/build.md') },
  {path: '/python/service/base', name: 'python_service_base', component: ()=>import('../views/docs/python/service/base.md') },
  {path: '/python/service/data', name: 'python_service_data', component: ()=>import('../views/docs/python/service/data.md') },
  {path: '/python/service/logs', name: 'python_service_logs', component: ()=>import('../views/docs/python/service/logs.md') },
  {path: '/python/service/token', name: 'python_service_token', component: ()=>import('../views/docs/python/service/token.md') },
  {path: '/python/service/socket', name: 'python_service_socket', component: ()=>import('../views/docs/python/service/socket.md') },
  {path: '/python/db/model', name: 'python_db_model', component: ()=>import('../views/docs/python/db/model.md') },
  {path: '/python/db/select', name: 'python_db_select', component: ()=>import('../views/docs/python/db/select.md') },
  {path: '/python/db/insert', name: 'python_db_insert', component: ()=>import('../views/docs/python/db/insert.md') },
  {path: '/python/db/update', name: 'python_db_update', component: ()=>import('../views/docs/python/db/update.md') },
  {path: '/python/db/delete', name: 'python_db_delete', component: ()=>import('../views/docs/python/db/delete.md') },
  {path: '/python/db/join', name: 'python_db_join', component: ()=>import('../views/docs/python/db/join.md') },
  {path: '/python/db/commit', name: 'python_db_commit', component: ()=>import('../views/docs/python/db/commit.md') },
  {path: '/python/library/curl', name: 'python_library_curl', component: ()=>import('../views/docs/python/library/curl.md') },
  {path: '/python/library/export', name: 'python_library_export', component: ()=>import('../views/docs/python/library/export.md') },
  {path: '/python/library/qrcode', name: 'python_library_qrcode', component: ()=>import('../views/docs/python/library/qrcode.md') },
  {path: '/python/library/redis', name: 'python_library_redis', component: ()=>import('../views/docs/python/library/redis.md') },
  {path: '/python/library/safety', name: 'python_library_safety', component: ()=>import('../views/docs/python/library/safety.md') },
  {path: '/python/library/socket', name: 'python_library_socket', component: ()=>import('../views/docs/python/library/socket.md') },
  {path: '/python/library/upload', name: 'python_library_upload', component: ()=>import('../views/docs/python/library/upload.md') },
  {path: '/python/util/util', name: 'python_util_util', component: ()=>import('../views/docs/python/util/util.md') },
  {path: '/python/util/url', name: 'python_util_url', component: ()=>import('../views/docs/python/util/url.md') },
  {path: '/python/util/base64', name: 'python_util_base64', component: ()=>import('../views/docs/python/util/base64.md') },
  {path: '/python/util/hash', name: 'python_util_hash', component: ()=>import('../views/docs/python/util/hash.md') },
  {path: '/python/util/type', name: 'python_util_type', component: ()=>import('../views/docs/python/util/type.md') },
  {path: '/python/util/os', name: 'python_util_os', component: ()=>import('../views/docs/python/util/os.md') },
  // SpringBoot
  {path: '/java/install/install', name: 'java_install_install', component: ()=>import('../views/docs/java/install/install.md') },
  {path: '/java/install/index', name: 'java_install_index', component: ()=>import('../views/docs/java/install/index.md') },
  {path: '/java/install/build', name: 'java_install_build', component: ()=>import('../views/docs/java/install/build.md') },
  {path: '/java/service/base', name: 'java_service_base', component: ()=>import('../views/docs/java/service/base.md') },
  {path: '/java/service/data', name: 'java_service_data', component: ()=>import('../views/docs/java/service/data.md') },
  {path: '/java/service/logs', name: 'java_service_logs', component: ()=>import('../views/docs/java/service/logs.md') },
  {path: '/java/service/token', name: 'java_service_token', component: ()=>import('../views/docs/java/service/token.md') },
  {path: '/java/service/socket', name: 'java_service_socket', component: ()=>import('../views/docs/java/service/socket.md') },
  {path: '/java/db/model', name: 'java_db_model', component: ()=>import('../views/docs/java/db/model.md') },
  {path: '/java/db/select', name: 'java_db_select', component: ()=>import('../views/docs/java/db/select.md') },
  {path: '/java/db/insert', name: 'java_db_insert', component: ()=>import('../views/docs/java/db/insert.md') },
  {path: '/java/db/update', name: 'java_db_update', component: ()=>import('../views/docs/java/db/update.md') },
  {path: '/java/db/delete', name: 'java_db_delete', component: ()=>import('../views/docs/java/db/delete.md') },
  {path: '/java/db/join', name: 'java_db_join', component: ()=>import('../views/docs/java/db/join.md') },
  {path: '/java/db/commit', name: 'java_db_commit', component: ()=>import('../views/docs/java/db/commit.md') },
  {path: '/java/library/curl', name: 'java_library_curl', component: ()=>import('../views/docs/java/library/curl.md') },
  {path: '/java/library/export', name: 'java_library_export', component: ()=>import('../views/docs/java/library/export.md') },
  {path: '/java/library/qrcode', name: 'java_library_qrcode', component: ()=>import('../views/docs/java/library/qrcode.md') },
  {path: '/java/library/redis', name: 'java_library_redis', component: ()=>import('../views/docs/java/library/redis.md') },
  {path: '/java/library/safety', name: 'java_library_safety', component: ()=>import('../views/docs/java/library/safety.md') },
  {path: '/java/library/socket', name: 'java_library_socket', component: ()=>import('../views/docs/java/library/socket.md') },
  {path: '/java/library/upload', name: 'java_library_upload', component: ()=>import('../views/docs/java/library/upload.md') },
  {path: '/java/util/util', name: 'java_util_util', component: ()=>import('../views/docs/java/util/util.md') },
  {path: '/java/util/url', name: 'java_util_url', component: ()=>import('../views/docs/java/util/url.md') },
  {path: '/java/util/base64', name: 'java_util_base64', component: ()=>import('../views/docs/java/util/base64.md') },
  {path: '/java/util/hash', name: 'java_util_hash', component: ()=>import('../views/docs/java/util/hash.md') },
  {path: '/java/util/type', name: 'java_util_type', component: ()=>import('../views/docs/java/util/type.md') },
  {path: '/java/util/os', name: 'java_util_os', component: ()=>import('../views/docs/java/util/os.md') },
  {path: '/java/util/dynamic', name: 'java_util_dynamic', component: ()=>import('../views/docs/java/util/dynamic.md') },
  {path: '/java/util/http', name: 'java_util_http', component: ()=>import('../views/docs/java/util/http.md') },
  // Gin
  {path: '/go/install/install', name: 'go_install_install', component: ()=>import('../views/docs/go/install/install.md') },
  {path: '/go/install/index', name: 'go_install_index', component: ()=>import('../views/docs/go/install/index.md') },
  {path: '/go/install/build', name: 'go_install_build', component: ()=>import('../views/docs/go/install/build.md') },
  {path: '/go/service/base', name: 'go_service_base', component: ()=>import('../views/docs/go/service/base.md') },
  {path: '/go/service/data', name: 'go_service_data', component: ()=>import('../views/docs/go/service/data.md') },
  {path: '/go/service/logs', name: 'go_service_logs', component: ()=>import('../views/docs/go/service/logs.md') },
  {path: '/go/service/token', name: 'go_service_token', component: ()=>import('../views/docs/go/service/token.md') },
  {path: '/go/service/socket', name: 'go_service_socket', component: ()=>import('../views/docs/go/service/socket.md') },
  {path: '/go/db/model', name: 'go_db_model', component: ()=>import('../views/docs/go/db/model.md') },
  {path: '/go/db/select', name: 'go_db_select', component: ()=>import('../views/docs/go/db/select.md') },
  {path: '/go/db/insert', name: 'go_db_insert', component: ()=>import('../views/docs/go/db/insert.md') },
  {path: '/go/db/update', name: 'go_db_update', component: ()=>import('../views/docs/go/db/update.md') },
  {path: '/go/db/delete', name: 'go_db_delete', component: ()=>import('../views/docs/go/db/delete.md') },
  {path: '/go/db/join', name: 'go_db_join', component: ()=>import('../views/docs/go/db/join.md') },
  {path: '/go/db/commit', name: 'go_db_commit', component: ()=>import('../views/docs/go/db/commit.md') },
  {path: '/go/library/curl', name: 'go_library_curl', component: ()=>import('../views/docs/go/library/curl.md') },
  {path: '/go/library/export', name: 'go_library_export', component: ()=>import('../views/docs/go/library/export.md') },
  {path: '/go/library/qrcode', name: 'go_library_qrcode', component: ()=>import('../views/docs/go/library/qrcode.md') },
  {path: '/go/library/redis', name: 'go_library_redis', component: ()=>import('../views/docs/go/library/redis.md') },
  {path: '/go/library/safety', name: 'go_library_safety', component: ()=>import('../views/docs/go/library/safety.md') },
  {path: '/go/library/socket', name: 'go_library_socket', component: ()=>import('../views/docs/go/library/socket.md') },
  {path: '/go/library/upload', name: 'go_library_upload', component: ()=>import('../views/docs/go/library/upload.md') },
  {path: '/go/util/util', name: 'go_util_util', component: ()=>import('../views/docs/go/util/util.md') },
  {path: '/go/util/url', name: 'go_util_url', component: ()=>import('../views/docs/go/util/url.md') },
  {path: '/go/util/base64', name: 'go_util_base64', component: ()=>import('../views/docs/go/util/base64.md') },
  {path: '/go/util/hash', name: 'go_util_hash', component: ()=>import('../views/docs/go/util/hash.md') },
  {path: '/go/util/type', name: 'go_util_type', component: ()=>import('../views/docs/go/util/type.md') },
  {path: '/go/util/os', name: 'go_util_os', component: ()=>import('../views/docs/go/util/os.md') },
  // Linux
  {path: '/linux/shell/index', name: 'linux_shell_index', component: ()=>import('../views/docs/linux/shell/index.md') },
  {path: '/linux/shell/ssl', name: 'linux_shell_ssl', component: ()=>import('../views/docs/linux/shell/ssl.md') },
  {path: '/linux/shell/macos', name: 'linux_shell_macos', component: ()=>import('../views/docs/linux/shell/macos.md') },
  {path: '/linux/shell/docker', name: 'linux_shell_docker', component: ()=>import('../views/docs/linux/shell/docker.md') },
  {path: '/linux/shell/mariadb', name: 'linux_shell_mariadb', component: ()=>import('../views/docs/linux/shell/mariadb.md') },
  {path: '/linux/shell/maxscale', name: 'linux_shell_maxscale', component: ()=>import('../views/docs/linux/shell/maxscale.md') },
  {path: '/linux/shell/pulsar', name: 'linux_shell_pulsar', component: ()=>import('../views/docs/linux/shell/pulsar.md') },
  {path: '/linux/shell/pyqt', name: 'linux_shell_pyqt', component: ()=>import('../views/docs/linux/shell/pyqt.md') },
  {path: '/linux/shell/elasticsearch', name: 'linux_shell_elasticsearch', component: ()=>import('../views/docs/linux/shell/elasticsearch.md') },
  {path: '/linux/service/git', name: 'linux_service_git', component: ()=>import('../views/docs/linux/service/git.md') },
  {path: '/linux/service/vpn', name: 'linux_service_vpn', component: ()=>import('../views/docs/linux/service/vpn.md') },
  {path: '/linux/centos/config', name: 'linux_centos_config', component: ()=>import('../views/docs/linux/centos/config.md') },
  {path: '/linux/centos/lnmp', name: 'linux_centos_lnmp', component: ()=>import('../views/docs/linux/centos/lnmp.md') },
  {path: '/linux/ubuntu/config', name: 'linux_ubuntu_config', component: ()=>import('../views/docs/linux/ubuntu/config.md') },
  {path: '/linux/ubuntu/lnmp', name: 'linux_ubuntu_lnmp', component: ()=>import('../views/docs/linux/ubuntu/lnmp.md') },
  {path: '/linux/archlinux/install', name: 'linux_archlinux_install', component: ()=>import('../views/docs/linux/archlinux/install.md') },
  {path: '/linux/archlinux/gnome', name: 'linux_archlinux_gnome', component: ()=>import('../views/docs/linux/archlinux/gnome.md') },
  {path: '/linux/archlinux/lnmp', name: 'linux_archlinux_lnmp', component: ()=>import('../views/docs/linux/archlinux/lnmp.md') },
  {path: '/linux/archlinux/github', name: 'linux_archlinux_github', component: ()=>import('../views/docs/linux/archlinux/github.md') },
]
/* 创建 */
export default createRouter({
  history: createWebHistory(),
  routes
})
